//
//  User.swift
//  ModelGen
//
//  Generated by [ModelGen]: https://github.com/hebertialmeida/ModelGen
//  Copyright © 2019 ModelGen. All rights reserved.
//

import Unbox

/// Definition of a User
public class User: Equatable {

    // MARK: Instance Variables

    public var currentCompanyId: Int
    public var companies: [Company]
    public var timezone: String?
    public var fullName: String
    public var createdAt: Date
    public var id: Int
    public var email: String
    public var avatar: Avatar

    // MARK: - Initializers

    public init(currentCompanyId: Int, companies: [Company], timezone: String?, fullName: String, createdAt: Date, id: Int, email: String, avatar: Avatar) {
        self.currentCompanyId = currentCompanyId
        self.companies = companies
        self.timezone = timezone
        self.fullName = fullName
        self.createdAt = createdAt
        self.id = id
        self.email = email
        self.avatar = avatar
    }

    public init(unboxer: Unboxer) throws {
        self.currentCompanyId = try unboxer.unbox(key: "current_company_id")
        self.companies = try unboxer.unbox(key: "companies")
        self.timezone =  unboxer.unbox(key: "timezone")
        self.fullName = try unboxer.unbox(key: "full_name")
        self.createdAt = try unboxer.unbox(key: "created_at", formatter: Date.serverDateFormatter())
        self.id = try unboxer.unbox(key: "id")
        self.email = try unboxer.unbox(key: "email")
        self.avatar = try unboxer.unbox(key: "avatar")
    }
}

// MARK: - Equatable

public func == (lhs: User, rhs: User) -> Bool {
    guard lhs.currentCompanyId == rhs.currentCompanyId else { return false }
    guard lhs.companies == rhs.companies else { return false }
    guard lhs.timezone == rhs.timezone else { return false }
    guard lhs.fullName == rhs.fullName else { return false }
    guard lhs.createdAt == rhs.createdAt else { return false }
    guard lhs.id == rhs.id else { return false }
    guard lhs.email == rhs.email else { return false }
    guard lhs.avatar == rhs.avatar else { return false }
    return true
}
