//
//  Company.swift
//  ModelGen
//
//  Generated by [ModelGen]: https://github.com/hebertialmeida/ModelGen
//  Copyright © 2019 ModelGen. All rights reserved.
//

import Unbox
import RocketData

/// Definition of a Company
public struct Company: BaseModel, Equatable {

    // MARK: Instance Variables

    public let id: Int
    public let name: String
    public let subdomain: String
    public let logo: URL?

    // MARK: - Initializers

    public init(id: Int, name: String, subdomain: String, logo: URL?) {
        self.id = id
        self.name = name
        self.subdomain = subdomain
        self.logo = logo
    }

    public init(unboxer: Unboxer) throws {
        self.id = try unboxer.unbox(key: "id")
        self.name = try unboxer.unbox(key: "name")
        self.subdomain = try unboxer.unbox(key: "subdomain")
        self.logo =  unboxer.unbox(key: "logo")
    }

    // MARK: - Rocket Data Model

    public var modelIdentifier: String? {
        return "Company:\(id)"
    }

    public func map(_ transform: (Model) -> Model?) -> Company? {
        return self
    }

    public func forEach(_ visit: (Model) -> Void) {
    }

    // MARK: - Builder

    public struct Builder {
        public var id: Int
        public var name: String
        public var subdomain: String
        public var logo: URL?

        public init(copy: Company) {
            id = copy.id
            name = copy.name
            subdomain = copy.subdomain
            logo = copy.logo
        }

        public func build() -> Company {
            return Company(id: id, name: name, subdomain: subdomain, logo: logo)
        }
    }
}

// MARK: - Equatable

public func == (lhs: Company, rhs: Company) -> Bool {
    guard lhs.id == rhs.id else { return false }
    guard lhs.name == rhs.name else { return false }
    guard lhs.subdomain == rhs.subdomain else { return false }
    guard lhs.logo == rhs.logo else { return false }
    return true
}