//
//  Company.swift
//  ModelGen
//
//  Generated by [ModelGen]: https://github.com/hebertialmeida/ModelGen
//  Copyright © 2019 ModelGen. All rights reserved.
//

import Unbox

/// Definition of a Company
public struct Company: Equatable {

    // MARK: Instance Variables

    public let id: Int
    public let logo: URL?
    public let name: String
    public let subdomain: String

    // MARK: - Initializers

    public init(id: Int, logo: URL?, name: String, subdomain: String) {
        self.id = id
        self.logo = logo
        self.name = name
        self.subdomain = subdomain
    }

    public init(unboxer: Unboxer) throws {
        self.id = try unboxer.unbox(key: "id")
        self.logo =  unboxer.unbox(key: "logo")
        self.name = try unboxer.unbox(key: "name")
        self.subdomain = try unboxer.unbox(key: "subdomain")
    }

    // MARK: - Builder

    public struct Builder {
        public var id: Int
        public var logo: URL?
        public var name: String
        public var subdomain: String

        public init(copy: Company) {
            id = copy.id
            logo = copy.logo
            name = copy.name
            subdomain = copy.subdomain
        }

        public func build() -> Company {
            return Company(id: id, logo: logo, name: name, subdomain: subdomain)
        }
    }
}

// MARK: - Equatable

public func == (lhs: Company, rhs: Company) -> Bool {
    guard lhs.id == rhs.id else { return false }
    guard lhs.logo == rhs.logo else { return false }
    guard lhs.name == rhs.name else { return false }
    guard lhs.subdomain == rhs.subdomain else { return false }
    return true
}
