//
//  Company.swift
//  ModelGen
//
//  Generated by [ModelGen]: https://github.com/hebertialmeida/ModelGen
//  Copyright © 2019 ModelGen. All rights reserved.
//

import Unbox

/// Definition of a Company
public struct Company: Equatable {

    // MARK: Instance Variables

    public let logo: URL?
    public let id: Int
    public let subdomain: String
    public let name: String

    // MARK: - Initializers

    public init(logo: URL?, id: Int, subdomain: String, name: String) {
        self.logo = logo
        self.id = id
        self.subdomain = subdomain
        self.name = name
    }

    public init(unboxer: Unboxer) throws {
        self.logo =  unboxer.unbox(key: "logo")
        self.id = try unboxer.unbox(key: "id")
        self.subdomain = try unboxer.unbox(key: "subdomain")
        self.name = try unboxer.unbox(key: "name")
    }

    // MARK: - Builder

    public struct Builder {
        public var logo: URL?
        public var id: Int
        public var subdomain: String
        public var name: String

        public init(copy: Company) {
            logo = copy.logo
            id = copy.id
            subdomain = copy.subdomain
            name = copy.name
        }

        public func build() -> Company {
            return Company(logo: logo, id: id, subdomain: subdomain, name: name)
        }
    }
}

// MARK: - Equatable

public func == (lhs: Company, rhs: Company) -> Bool {
    guard lhs.logo == rhs.logo else { return false }
    guard lhs.id == rhs.id else { return false }
    guard lhs.subdomain == rhs.subdomain else { return false }
    guard lhs.name == rhs.name else { return false }
    return true
}
